version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: retailpulse-db
    environment:
      POSTGRES_USER: retailuser
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: retailpulse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: